kr210:
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a1
    pid: {p: 100, i: 100, d: 500}

  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a2
    pid: {p: 100, i: 100, d: 2000}

  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a3
    pid: {p: 100, i: 50, d: 1000}

  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a4
    pid: {p: 100, i: 50, d: 200}

  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a5
    pid: {p: 100, i: 50, d: 70}

  joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a6
    pid: {p: 100, i: 50, d: 70}


 
